2 small modifications to fix ./configure and make config on Mac OS X. ./configure's macros were barfing on cases where SDL_main.h redefined main. The menuconfig script is broken due to ncurses issues. The configure script works assuming it runs under bash correctly.

diff --git a/pgserver/configscript/Configure b/pgserver/configscript/Configure
--- a/pgserver/configscript/Configure
+++ b/pgserver/configscript/Configure
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #
 # This script is used to configure the Linux kernel.
 #
@@ -56,7 +56,9 @@
 # better string handling, but alas, bash is the only scripting language
 # that I can be reasonable sure everybody has on their linux machine.
 #
-[ -z "$BASH" ] && { echo "Configure requires bash" 1>&2; exit 1; }
+
+# Commented out by Micah. This fails on Mac OS X even with bash installed
+#[ -z "$BASH" ] && { echo "Configure requires bash" 1>&2; exit 1; }
 
 # Disable filename globbing once and for all.
 # Enable function cacheing.
